package model;

import model.domain.OrderList;
import model.domain.RoomList;
import model.domain.UserList;
import model.domain.error.ErrorInterface;
import model.domain.hotel.*;
import model.domain.order.OrderInterface;
import model.domain.room.RoomInterface;
import model.domain.room.TimeRangeList;
import model.domain.room.timeRange.TimeRangeInterface;
import model.domain.user.AccountInformation;
import model.domain.user.UserInterface;
import utility.NamedPropertyChangeSubject;

public interface BookingModel extends NamedPropertyChangeSubject
{
  void updateError(String error);
  ErrorInterface addNewUser(AccountInformation accountInformation);
  ErrorInterface updateUser(UserInterface newUser);
  UserInterface getUser(String email);
  UserInterface getUser(int index);
  UserList getUserList();
  void addNewRoom(int roomNumber,String type);
  void updateRoom(RoomInterface oldRoom,RoomInterface newRoom);
  void updateRoomType(RoomInterface room,String newType);
  ErrorInterface updateRoomBookedTimeRange(RoomInterface room,TimeRangeList timeRangeList);
  RoomInterface getRoom(RoomInterface room);
  RoomInterface getRoomByRoomNumber(int roomNumber);
  RoomInterface getRoomByIndex(int index);
  RoomList getRoomsByType(String type);
  RoomList getRoomsByFreeTimeRangeList(TimeRangeList timeRangeList);
  RoomList getRooms();
  void removeRoom(RoomInterface room);
  void removeRoomByRoomNumber(int roomNumber);
  void removeRoomByIndex(int index);
  void removeRoomsByType(String type);
  ErrorInterface addNewOrder(OrderInterface newOrder);
  ErrorInterface updateOrder(OrderInterface newOrder);
  OrderInterface getOrderByIndex(int index);
  OrderInterface getOrder(int orderNumber);
  OrderList getOrders();
  OrderList getOrders(UserInterface user);
  OrderList getOrders(RoomInterface room);
  OrderList getOrders(RoomInformation roomInformation);
  OrderList getOrders(TimeRangeInterface timeRange);
  OrderList getOrders(TimeRangeList timeRangeList);
  void cancelOrderByIndex(int index);
  void cancelOrder(int orderNumber);
  void cancelOrders(UserInterface user);
  void cancelOrders(RoomInterface room);
  void cancelOrders(RoomInformation roomInformation);
  void cancelOrders(TimeRangeInterface timeRange);
  void updateHotel(String name,String address,String contactNumber,String facilities,String characteristic,String description,String rules,int checkIn,int checkOut);
  HotelInterface getHotel();
  RoomInformationList getRoomInformationList();
  RoomInformation getRoomInformationByIndex(int index);
  void addRoomInformation(RoomInformation roomInformation);
  void updateRoomInformation(RoomInformation oldRoomInformation,RoomInformation newRoomInformation);
  void removeRoomInformation(RoomInformation roomInformation);
  void removeRoomInformation(String type);
  void addOptionService(OptionService optionService);
  void updateOptionService(OptionService oldOptionService,OptionService newOptionService);
  void removeOptionService(OptionService optionService);
  void removeOptionService(int index);
  void removeOptionService(String serviceType);
  OptionServiceList getOptionServiceList();
  OptionService getOptionServiceByIndex(int index);
  OptionService getOptionServiceByServiceType(String serviceType);
}
